environment:
  JRE6_HOME: $(ProgramFiles)\Java\jdk1.6.0\jre

  matrix:
    - platform: x86
      JAVA_HOME: $(ProgramFiles) (x86)\Java\jdk1.6.0
      ANT_VERSION: 1.9.8
    - platform: x86
      JAVA_HOME: $(ProgramFiles) (x86)\Java\jdk1.7.0
      ANT_VERSION: 1.9.8
    - platform: x86
      JAVA_HOME: $(ProgramFiles) (x86)\Java\jdk1.8.0
      ANT_VERSION: 1.10.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.6.0
      ANT_VERSION: 1.9.8
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.7.0
      ANT_VERSION: 1.9.8
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0
      ANT_VERSION: 1.10.0

install:
  - ps: if (!(Test-Path -Path ($env:ChocolateyInstall + '\lib\ant\apache-ant-' + $env:ANT_VERSION))) { cinst ant -i --version $env:ANT_VERSION }
  - cmd: PATH %ChocolateyInstall%\lib\ant\apache-ant-%ANT_VERSION%\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: java -Xmx32m -version
  - cmd: javac -J-Xmx32m -version
  - cmd: ant -version

cache:
  - $(ChocolateyInstall)\lib\ant -> .appveyor.yml

build_script:
  - ant all

after_build:
  - ps: If ($env:APPVEYOR_REPO_TAG -eq 'true' -and $env:JAVA_HOME -eq ($env:ProgramFiles + '\Java\jdk1.8.0')) { $env:ARTIFACTS_PATH = 'target\dist\*.jar' }

artifacts:
  - path: $(ARTIFACTS_PATH)
    type: file
