environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.6.0
      JRE6_HOME: C:\Program Files\Java\jdk1.6.0\jre

    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
      JRE6_HOME: C:\Program Files\Java\jdk1.6.0\jre

    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      JRE6_HOME: C:\Program Files\Java\jdk1.6.0\jre

install:
  - cmd: SET ANT_VERSION=1.9.8
  - ps: if (!(Test-Path -Path 'C:\ProgramData\chocolatey\lib\ant\apache-ant-$env:ANT_VERSION\')) { cinst ant -i -Version $env:ANT_VERSION }
  - cmd: SET PATH=C:\ProgramData\chocolatey\lib\ant\apache-ant-$env:ANT_VERSION\bin;%JAVA_HOME%\bin;%PATH%

cache:
  - C:\ProgramData\chocolatey\lib\ant\apache-ant-$env:ANT_VERSION

platform:
  - x86
  - x64

build_script:
  - ant all
