clone_depth: 50

environment:
  JRE6_HOME: $(ProgramFiles)\Java\jdk1.6.0\jre

  matrix:
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.6.0
      ANT_VERSION: 1.9.8
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.7.0
      ANT_VERSION: 1.9.8
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.8.0
      ANT_VERSION: 1.10.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.6.0
      ANT_VERSION: 1.9.8
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.7.0
      ANT_VERSION: 1.9.8
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0
      ANT_VERSION: 1.10.0

cache:
  - $(ChocolateyInstall)\lib\ant -> .appveyor.yml

install:
  - ps: if (!(Test-Path -Path ($env:ChocolateyInstall + '\lib\ant\apache-ant-' + $env:ANT_VERSION))) { cinst ant -i --version $env:ANT_VERSION }
  - cmd: PATH %ChocolateyInstall%\lib\ant\apache-ant-%ANT_VERSION%\bin;%JAVA_HOME%\bin;%PATH%

before_build:
  - cmd: java -Xmx32m -version
  - cmd: javac -J-Xmx32m -version
  - cmd: ant -version

build_script:
  - ant all

after_build:
  - ps: If ($env:APPVEYOR_REPO_TAG -eq 'true' -and $env:JAVA_HOME -eq ($env:ProgramFiles + '\Java\jdk1.8.0')) { $env:ARTIFACTS_PATH = 'target\*.*' }

artifacts:
  - path: $(ARTIFACTS_PATH)
    type: file

deploy:
  description: 'Autogenerated'
  provider: GitHub
  auth_token:
    secure: iZF8b6d29Wk2VAubvw8tEwOMt0kB0Krq2e0Ie0Up15EfEfEBnvgs05/LbjhIODWi
  draft: true
  on:
    appveyor_repo_tag: true
