version: '{build}'

clone_depth: 50

environment:
  MVN_VERSION: 3.5.0

  matrix:
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.7.0
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.7.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0

cache:
  - $(ChocolateyInstall)\lib -> .appveyor.yml
  - $(ChocolateyInstall)\bin -> .appveyor.yml

install:
  - ps: cinst maven -i --version $env:MVN_VERSION
  - cmd: PATH %ChocolateyInstall%\lib\maven\apache-maven-%MVN_VERSION%\bin;%PATH%

before_build:
  - cmd: java -Xmx32m -version
  - cmd: javac -J-Xmx32m -version
  - cmd: mvn -version

build_script:
  - mvn clean install

after_build:
  - ps: If ($env:APPVEYOR_REPO_TAG -eq 'true' -and $env:JAVA_HOME -eq ($env:ProgramFiles + '\Java\jdk1.8.0')) { $env:ARTIFACTS_PATH = 'target\*.*' }

artifacts:
  - path: $(ARTIFACTS_PATH)
    type: file

deploy:
  description: 'Autogenerated'
  provider: GitHub
  auth_token:
    secure: iZF8b6d29Wk2VAubvw8tEwOMt0kB0Krq2e0Ie0Up15EfEfEBnvgs05/LbjhIODWi
  draft: true
  on:
    appveyor_repo_tag: true
