image: Visual Studio 2019

version: '{build}'

clone_depth: 50

environment:
  matrix:
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0
      ARTIFACTS_PATH: target\*.jar
      CHECKSUMS_PATH: target\checksums.md
      VT_API_KEY:
        secure: 3sqJDjLAS708tR/LiAqKLZTnLLrhGJuWVzzI4nCjLbUUsZB+PPRG3y0BWWnMo14CDhBT4v6yjHTA23RdopoHDWJlBcGhKELKZOLhHsnJLU8=
      GITHUB_SITE_MAVEN_PLUGIN_TOKEN:
        secure: iZF8b6d29Wk2VAubvw8tEwOMt0kB0Krq2e0Ie0Up15EfEfEBnvgs05/LbjhIODWi

build_script:
  - mvn clean install -e -B -V

after_build:
  - cmd: IF DEFINED GITHUB_SITE_MAVEN_PLUGIN_TOKEN mvn deploy -DskipTests -e -B -V
  - cmd: IF DEFINED VT_API_KEY FOR %%f IN (%ARTIFACTS_PATH%) DO ECHO Submitting file "%%f" to VirusTotal... & curl -v -F "file=@%%f" -F apikey=%VT_API_KEY% https://www.virustotal.com/vtapi/v2/file/scan & ECHO File "%%f" submitted to VirusTotal. & TIMEOUT 15 /NOBREAK

artifacts:
  - path: $(ARTIFACTS_PATH)
    type: file
  - path: $(CHECKSUMS_PATH)
    type: file

deploy:
  description: 'Autogenerated'
  provider: GitHub
  auth_token:
    secure: iZF8b6d29Wk2VAubvw8tEwOMt0kB0Krq2e0Ie0Up15EfEfEBnvgs05/LbjhIODWi
  draft: true
  on:
    appveyor_repo_tag: true
